In [4]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv('COVID-19_CBC_Data.csv')

In [10]:
data = data[['Admission_DATE ','Outcome','Patient Age','Gender','What kind of Treatment provided ','Ventilated (Y/N)','Red blood cell distribution width'
             ,'Monocytes(%)','White blood cell count','Platelet Count','Platelet Count','Lymphocyte Count','Neutrophils Count']]

In [14]:
X = data.drop(['Outcome'], axis=1)
X.head()

,Admission_DATE,Patient Age,Gender,What kind of Treatment provided,Ventilated (Y/N),Red blood cell distribution width,Monocytes(%),White blood cell count,Platelet Count,Platelet Count,Lymphocyte Count,Neutrophils Count
0,8/10/2020,51,Male,"antibiotics, O2",Yes,13.2,3.3,21.00,462.00,462.00,0.44,19.43
1,7/24/2020,65,Female,"Paracetamol, Antibiotics, O2",Yes,40.0,3.0,8.79,180.66,180.66,4.39,7.56
2,7/22/2020,32,Male,"Antibiotics, O2",No,11.7,5.3,9.90,336.00,336.00,3.47,5.34
3,7/19/2020,36,Female,"Antibiotics, O2",No,13.0,5.0,9.95,240.10,240.10,0.80,8.66
4,7/18/2020,46,Male,"Paracetamol, Antibiotics, O2",No,31.0,3.0,14.15,236.58,236.58,7.93,13.02

In [16]:
X = pd.get_dummies(X, drop_first=True)

In [18]:
X.head()

,Patient Age,Red blood cell distribution width,Monocytes(%),White blood cell count,Platelet Count,Platelet Count,Lymphocyte Count,Neutrophils Count,Admission_DATE _06/10/2020,Admission_DATE _06/11/2020,...,"What kind of Treatment provided _Antibiotics, O5","What kind of Treatment provided _Antibiotics, O6","What kind of Treatment provided _Antibiotics, O7","What kind of Treatment provided _Antibiotics, O8","What kind of Treatment provided _Antibiotics, O9","What kind of Treatment provided _Antibiotics, O2","What kind of Treatment provided _Paracetamol, Antibiotics, O2",What kind of Treatment provided _antibiotics,"What kind of Treatment provided _antibiotics, O2",Ventilated (Y/N)_Yes
0,51,13.2,3.3,21.00,462.00,462.00,0.44,19.43,False,False,...,False,False,False,False,False,False,False,False,True,True
1,65,40.0,3.0,8.79,180.66,180.66,4.39,7.56,False,False,...,False,False,False,False,False,False,True,False,False,True
2,32,11.7,5.3,9.90,336.00,336.00,3.47,5.34,False,False,...,False,False,False,False,False,True,False,False,False,False
3,36,13.0,5.0,9.95,240.10,240.10,0.80,8.66,False,False,...,False,False,False,False,False,True,False,False,False,False
4,46,31.0,3.0,14.15,236.58,236.58,7.93,13.02,False,False,...,False,False,False,False,False,False,True,False,False,False

In [20]:
X = X.assign(const = 1)

In [34]:
y = data['Outcome']

In [36]:
y.head()

0    Not Recovered
1    Not Recovered
2        Recovered
3        Recovered
4        Recovered
Name: Outcome, dtype: object